<?php 
 include('header.php');
?>

<div class="faq" style="text-align: center; font-size: 25pt; margin-top: 60px; margin-bottom: 20px; ">
  <b>PRIVACY POLICY</b>
  <hr>

  <p style="font-size : 15pt; text-align : left; margin-left : 40px; width : 95%;">Dengan menggunakan situs ini. Anda menerima semua kegiatan yang dijelaskan dalam kebijakan privasi berikut ini. Kegiatan ini dapat diubah, tetapi perubahan akan diumumkan di situs ini dan perubahan hanya akan berlaku untuk kegiatan dan informasi yang akan datang, bukan yang sudah terjadi. Anda dianjurkan untuk membaca kebijakan privasi setiap kali mengunjungi situs untuk memastikan bahwa anda memahami bagaimana informasi pribadi yang anda berikan akan digunakan. Catatan: tata cara privasi yang ditetapkan dalam kebijakan privasi ini berlaku untuk situs ini saja. Jika anda mengakses situs lain, harap membaca kebijakan privasi yang terpampang pada situs tersebut.</p>
  <p style="font-size : 15pt; text-align : left; margin-left : 40px; width : 95%;"><b>Pengumpulan Informasi</b></p>
  <p style="font-size : 15pt; text-align : left; margin-left : 40px; width : 95%;">MITIX Indonesia mengumpulkan informasi pribadi, seperti nama, alamat untuk bersurat, alamat email, dan lain-lain, ketika diajukan secara sukarela oleh pengunjung kami. Informasi yang anda berikan digunakan untuk memenuhi permintaan khusus anda. Informasi ini hanya digunakan untuk memenuhi permintaan khusus anda, kecuali anda memberikan izin kepada kami untuk menggunakannya untuk kepentingan lain, seperti menambahkan anda ke salah satu mailing list kami.</p>
  <p style="font-size : 15pt; text-align : left; margin-left : 40px; width : 95%;"><b>Pelacakan (Cookie) Teknologi</b></P>
  <p style="font-size : 15pt; text-align : left; margin-left : 40px; width : 95%;">Situs MITIX Indonesia dapat menggunakan cookie dan teknologi pelacakan tergantung pada fitur yang ditawarkan. Teknologi pelacakan dan cookie bermanfaat untuk mengumpulkan informasi seperti jenis browser dan sistem operasional, mendata jumlah pengunjung situs dan memahami cara pengunjung menggunakan situs. Cookie juga dapat membantu menyesuaikan situs untuk pengunjung. Informasi pribadi tidak dapat dikumpulkan melalui cookie dan teknologi pelacak lainnya. Namun, jika sebelumnya anda memberikan informasi identitas pribadi, cookie dapat terhubung ke informasi tersebut. Jenis cookie agregat dan pelacakan informasi dapat diinformasikan dengan pihak ketiga.</P>
  <p style="font-size : 15pt; text-align : left; margin-left : 40px; width : 95%;"><b>Distribusi Informasi</b></P>
  <p style="font-size : 15pt; text-align : left; margin-left : 40px; width : 95%;">MITIX Indonesia dapat berbagi informasi dengan instansi pemerintah atau perusahaan lainnya yang membantu kami dalam hal mencegah penipuan atau investigasi. Kami dapat melakukannya ketika: (1) diizinkan atau diharuskan oleh hukum, atau, (2) mencoba untuk melindungi atau mencegah penipuan atau hal yang berpotensi untuk berujung pada penipuan atau transaksi yang tidak sah, atau, (3) menyelidiki penipuan yang telah terjadi. Informasi ini tidak diberikan kepada perusahaan-perusahaan lain untuk kepentingan pemasaran.</p>
  <p style="font-size : 15pt; text-align : left; margin-left : 40px; width : 95%;"><b>Komitmen Untuk Keamanan Data</b></p>
  <p style="font-size : 15pt; text-align : left; margin-left : 40px; width : 95%;">Informasi pribadi anda disimpan secara aman. Hanya karyawan, agen dan kontraktor (yang telah setuju untuk menyimpan informasi anda secara aman dan rahasia) akan memiliki akses ke informasi ini. Semua e-mail dan newsletter dari situs ini memberikan pilihan kepada anda untuk tidak disertakan ke dalam daftar mailing list berikutnya.</p>
