<?php 
 include('header.php');
?>

<div class="faq" style="text-align: center; font-size: 25pt; margin-top: 60px; margin-bottom: 20px; ">
  <b>TERMS OF SERVICE</b>

  <p style="font-size : 15pt; text-align : left; margin-left : 40px; width : 95%;">Dengan membuka, membaca, mengakses, atau mengunduh informasi, data, atau material apapun yang ada dalam website ini, sebagian atau seluruhnya, dengan cara apapun, maka anda menyatakan telah memahami dan setuju untuk terikat oleh ketentuan-ketentuan dalam ketentuan penggunaan ini.</p>
  <p style="font-size : 15pt; text-align : left; margin-left : 40px; width : 95%;">Segala informasi, data, atau material apapun yang ada dalam website ini adalah hak milik dari PT. Karya Cipta Agung (Founder MITIX) dan milik pemegang hak resmi atas merek, logo, material yang bersangkutan dan dilindungi sebagai Hak Kekayaan Intelektual berdasarkan ketentuan perundang-undangan yang berlaku.( UU ITE Pasal 25)</p>
  <p style="font-size : 15pt; text-align : left; margin-left : 40px; width : 95%;">MITIX Indonesia memberikan izin penggunaan atas informasi, material, data, data film, data jadwal film, data teater atau bioskop, layanan dan turunannya dalam bentuk apapun yang ada dalam website ini (selanjutnya disebut Data Website), dengan ketentuan sebagai berikut:</p>
  <p style="font-size : 15pt; text-align : left; margin-left : 40px; width : 95%;">A. Izin penggunaan diberikan dengan ketentuan</P>
  <p style="font-size : 15pt; text-align : left; margin-left : 60px; width : 95%;">1. Penggunaan pribadi <br>2. Penggunaan yang wajar tidak berlebihan menurut penilaian MITIX Indonesia secara sendiri</P>
  <p style="font-size : 15pt; text-align : left; margin-left : 40px; width : 95%;">B. Dilarang</P>
  <p style="font-size : 15pt; text-align : left; margin-left : 60px; width : 95%;">1. Menggunakan Data Website untuk kepentingan komersial<br>2. Menerbitkan ulang, sebagian atau seluruh Data Website maupun turunannya, untuk keperluan apapun, baik untuk memperoleh keuntungan dari penerbitan tersebut maupun tidak<br>3. Memberikan ijin, hak guna, menjual, menyewakan, meminjamkan, meminjam atau menyewa Data Website dan turunannya dalam bentuk apapun<br>4. Dengan sengaja dan/atau tanpa hak mengakses data website dengan melanggar, menerobos, melampaui, atau menjebol system pengamanan. (UU ITE Pasal 30 (3))<br>5. Dengan sengaja dan/atau tanpa hak melakukan penyadapan data website (UU ITE Pasal 31 (1))<br>6. Dengan sengaja / tanpa hak melakukan intersepsi atas transmisi informasi data website sehingga menyebabkan perubahan, penghilangan data. (UU ITE Pasal 32)<br>7. Dengan sengaja dan/atau tanpa hak menggunakan data website sehingga terjadi gangguan. (UU ITE Pasal 33)<br>8. Setiap Orang dengan sengaja dan tanpa hak atau melawan hukum memproduksi, menjual, mengadakan untuk digunakan, mengimpor, mendistribusikan kecuali untuk penelitian. (UU ITE Pasal 34)</p>
  <p style="font-size : 15pt; text-align : left; margin-left : 40px; width : 95%;">Jika Anda tidak setuju pada sebagian saja dari Ketentuan Penggunaan ini, Anda harus berhenti menggunakan Website dan Data Website, dan semua salinan Data Website harus dihancurkan dengan segera. Setiap pelanggaran dalam ketentuan penggunaan data website dapat dijadikan tuntutan hukum berdasarkan Undang-Undang No. 11 Tahun 2008 tentang Informasi dan Transaksi Elektronik.</p>
  <p style="font-size : 15pt; text-align : left; margin-left : 40px; width : 95%;">MITIX Indonesia dapat memperbarui Ketentuan Penggunaan ini dari waktu ke waktu. Periksalah selalu Ketentuan Penggunaan ini sebelum menggunakan Website.</p>
